import { WordDictionary } from '../../../common/interface/interface';

const object: WordDictionary[] = [
  {
    id: '5e9f5ee35eb9e72bc21af4a0',
    group: 0,
    page: 0,
    word: 'alcohol',
    image: 'files/01_0002.jpg',
    audio: 'files/01_0002.mp3',
    audioMeaning: 'files/01_0002_meaning.mp3',
    audioExample: 'files/01_0002_example.mp3',
    textMeaning: '<i>Alcohol</i> is a type of drink that can make people drunk.',
    textExample: 'A person should not drive a car after he or she has been drinking <b>alcohol</b>.',
    transcription: '[ǽlkəhɔ̀ːl]',
    textExampleTranslate: 'Человек не должен водить машину после того, как он выпил алкоголь',
    textMeaningTranslate: 'Алкоголь - это тип напитка, который может сделать людей пьяными',
    wordTranslate: 'алкоголь',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a6',
    group: 0,
    page: 0,
    word: 'camera',
    image: 'files/01_0007.jpg',
    audio: 'files/01_0007.mp3',
    audioMeaning: 'files/01_0007_meaning.mp3',
    audioExample: 'files/01_0007_example.mp3',
    textMeaning: 'A <i>camera</i> is a piece of equipment that takes pictures.',
    textExample: 'I brought my <b>camera</b> on my vacation.',
    transcription: '[kǽmərə]',
    textExampleTranslate: 'Я принес свою камеру в отпуск',
    textMeaningTranslate: 'Камера - это часть оборудования, которая делает снимки',
    wordTranslate: 'камера',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ab',
    group: 0,
    page: 0,
    word: 'invite',
    image: 'files/01_0012.jpg',
    audio: 'files/01_0012.mp3',
    audioMeaning: 'files/01_0012_meaning.mp3',
    audioExample: 'files/01_0012_example.mp3',
    textMeaning: 'To <i>invite</i> is to ask someone to come to a place or event.',
    textExample: 'I will <b>invite</b> my friends to my birthday party.',
    transcription: '[inváit]',
    textExampleTranslate: 'Я приглашаю своих друзей на мой день рождения',
    textMeaningTranslate: 'Пригласить - это попросить кого-нибудь прийти на место или событие',
    wordTranslate: 'пригласить',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ad',
    group: 0,
    page: 0,
    word: 'travel',
    image: 'files/01_0015.jpg',
    audio: 'files/01_0015.mp3',
    audioMeaning: 'files/01_0015_meaning.mp3',
    audioExample: 'files/01_0015_example.mp3',
    textMeaning: 'To <i>travel</i> is to go to a faraway place on vacation or business.',
    textExample: 'They will <b>travel</b> to Argentina this summer.',
    transcription: '[trǽvəl]',
    textExampleTranslate: 'Этим летом они отправятся в Аргентину',
    textMeaningTranslate: 'Путешествовать - это отправиться в далекое место на отдых или по делам',
    wordTranslate: 'путешествовать',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b1',
    group: 0,
    page: 0,
    word: 'weather',
    image: 'files/01_0018.jpg',
    audio: 'files/01_0018.mp3',
    audioMeaning: 'files/01_0018_meaning.mp3',
    audioExample: 'files/01_0018_example.mp3',
    textMeaning: '<i>Weather</i> is the temperature and the state of the outdoors.',
    textExample: 'Today’s <b>weather</b> is rainy and cloudy.',
    transcription: '[weðər]',
    textExampleTranslate: 'Сегодня погода дождливая и облачная',
    textMeaningTranslate: 'Погода это температура и состояние на улице',
    wordTranslate: 'погода',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a1',
    group: 0,
    page: 0,
    word: 'agree',
    image: 'files/01_0001.jpg',
    audio: 'files/01_0001.mp3',
    audioMeaning: 'files/01_0001_meaning.mp3',
    audioExample: 'files/01_0001_example.mp3',
    textMeaning: 'To <i>agree</i> is to have the same opinion or belief as another person.',
    textExample: 'The students <b>agree</b> they have too much homework.',
    transcription: '[əgríː]',
    textExampleTranslate: 'Студенты согласны, что у них слишком много домашней работы',
    textMeaningTranslate: 'Согласиться - значит иметь то же мнение или убеждение, что и другой человек',
    wordTranslate: 'согласна',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a4',
    group: 0,
    page: 0,
    word: 'August',
    image: 'files/01_0004.jpg',
    audio: 'files/01_0004.mp3',
    audioMeaning: 'files/01_0004_meaning.mp3',
    audioExample: 'files/01_0004_example.mp3',
    textMeaning: '<i>August</i> is the eighth month of the year.',
    textExample: 'Is your birthday in <b>August</b>?',
    transcription: '[ɔ́ːgəst]',
    textExampleTranslate: 'У тебя день рождения в августе?',
    textMeaningTranslate: 'Август - восьмой месяц года',
    wordTranslate: 'август',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a8',
    group: 0,
    page: 0,
    word: 'catch',
    image: 'files/01_0009.jpg',
    audio: 'files/01_0009.mp3',
    audioMeaning: 'files/01_0009_meaning.mp3',
    audioExample: 'files/01_0009_example.mp3',
    textMeaning: 'To <i>catch</i> is to grab or get something.',
    textExample: 'Did you <b>catch</b> the ball during the baseball game?',
    transcription: '[kætʃ]',
    textExampleTranslate: 'Вы поймали мяч во время игры в бейсбол?',
    textMeaningTranslate: 'Поймать - значит схватить или получить что-то',
    wordTranslate: 'поймать',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4aa',
    group: 0,
    page: 0,
    word: 'enjoy',
    image: 'files/01_0011.jpg',
    audio: 'files/01_0011.mp3',
    audioMeaning: 'files/01_0011_meaning.mp3',
    audioExample: 'files/01_0011_example.mp3',
    textMeaning: 'To <i>enjoy</i> is to like something.',
    textExample: 'The woman <b>enjoys</b> riding her bicycle.',
    transcription: '[indʒɔ́i]',
    textExampleTranslate: 'Женщина любит кататься на велосипеде',
    textMeaningTranslate: 'Наслаждаться значит любить что-то',
    wordTranslate: 'наслаждаться',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ae',
    group: 0,
    page: 0,
    word: 'love',
    image: 'files/01_0013.jpg',
    audio: 'files/01_0013.mp3',
    audioMeaning: 'files/01_0013_meaning.mp3',
    audioExample: 'files/01_0013_example.mp3',
    textMeaning: 'To <i>love</i> is to like something or someone a lot.',
    textExample: 'I <b>love</b> my family very much.',
    transcription: '[lʌv]',
    textExampleTranslate: 'Я очень люблю свою семью',
    textMeaningTranslate: 'Любить значит любить что-то или кого-то много',
    wordTranslate: 'любовь',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4af',
    group: 0,
    page: 0,
    word: 'typical',
    image: 'files/01_0016.jpg',
    audio: 'files/01_0016.mp3',
    audioMeaning: 'files/01_0016_meaning.mp3',
    audioExample: 'files/01_0016_example.mp3',
    textMeaning: 'If something is <i>typical</i>, it is normal, or something that usually happens.',
    textExample: 'My <b>typical</b> breakfast is toast and eggs.',
    transcription: '[típikəl]',
    textExampleTranslate: 'Мой типичный завтрак - тост и яйца',
    textMeaningTranslate: 'Если что-то типичное, это нормально, или что-то, что обычно происходит',
    wordTranslate: 'типичный',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b0',
    group: 0,
    page: 0,
    word: 'visit',
    image: 'files/01_0017.jpg',
    audio: 'files/01_0017.mp3',
    audioMeaning: 'files/01_0017_meaning.mp3',
    audioExample: 'files/01_0017_example.mp3',
    textMeaning: 'To <i>visit</i> is to go and spend time in another place or see another person.',
    textExample: 'She wants to <b>visit</b> her grandmother.',
    transcription: '[vízit]',
    textExampleTranslate: 'Она хочет навестить свою бабушку',
    textMeaningTranslate: 'Посетить - значит пойти и провести время в другом месте или увидеть другого человека',
    wordTranslate: 'посещение',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b2',
    group: 0,
    page: 0,
    word: 'wine',
    image: 'files/01_0020.jpg',
    audio: 'files/01_0020.mp3',
    audioMeaning: 'files/01_0020_meaning.mp3',
    audioExample: 'files/01_0020_example.mp3',
    textMeaning: '<i>Wine</i> is an alcoholic drink made from grapes.',
    textExample: 'The store carried both red and white <b>wine</b>.',
    transcription: '[wain]',
    textExampleTranslate: 'В магазине было красное и белое вино',
    textMeaningTranslate: 'Вино - это алкогольный напиток из винограда',
    wordTranslate: 'вино',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a3',
    group: 0,
    page: 0,
    word: 'arrive',
    image: 'files/01_0003.jpg',
    audio: 'files/01_0003.mp3',
    audioMeaning: 'files/01_0003_meaning.mp3',
    audioExample: 'files/01_0003_example.mp3',
    textMeaning: 'To <i>arrive</i> is to get somewhere.',
    textExample: 'They <b>arrived</b> at school at 7 a.m.',
    transcription: '[əráiv]',
    textExampleTranslate: 'Они прибыли в школу в 7 часов утра',
    textMeaningTranslate: 'Приехать значит попасть куда-то',
    wordTranslate: 'прибыть',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a5',
    group: 0,
    page: 0,
    word: 'breakfast',
    image: 'files/01_0006.jpg',
    audio: 'files/01_0006.mp3',
    audioMeaning: 'files/01_0006_meaning.mp3',
    audioExample: 'files/01_0006_example.mp3',
    textMeaning: '<i>Breakfast</i> is the morning meal.',
    textExample: 'I ate eggs for <b>breakfast</b>.',
    transcription: '[brekfəst]',
    textExampleTranslate: 'Я ел яйца на завтрак',
    textMeaningTranslate: 'Завтрак - это утренняя трапеза',
    wordTranslate: 'завтрак',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a9',
    group: 0,
    page: 0,
    word: 'duck',
    image: 'files/01_0010.jpg',
    audio: 'files/01_0010.mp3',
    audioMeaning: 'files/01_0010_meaning.mp3',
    audioExample: 'files/01_0010_example.mp3',
    textMeaning: 'A <i>duck</i> is a small water bird.',
    textExample: 'People feed <b>ducks</b> at the lake.',
    transcription: '[dʌk]',
    textExampleTranslate: 'Люди кормят уток у озера',
    textMeaningTranslate: 'Утка - маленькая водяная птица',
    wordTranslate: 'утка',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ac',
    group: 0,
    page: 0,
    word: 'month',
    image: 'files/01_0014.jpg',
    audio: 'files/01_0014.mp3',
    audioMeaning: 'files/01_0014_meaning.mp3',
    audioExample: 'files/01_0014_example.mp3',
    textMeaning: 'A <i>month</i> is one of 12 periods of time in one year.',
    textExample: 'January is the first <b>month</b> of the year.',
    transcription: '[mʌnθ]',
    textExampleTranslate: 'январь - первый месяц года',
    textMeaningTranslate: 'Месяц - это один из 12 периодов времени в году',
    wordTranslate: 'месяц',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b3',
    group: 0,
    page: 0,
    word: 'week',
    image: 'files/01_0019.jpg',
    audio: 'files/01_0019.mp3',
    audioMeaning: 'files/01_0019_meaning.mp3',
    audioExample: 'files/01_0019_example.mp3',
    textMeaning: 'A <i>week</i> is a period of time that is seven days long.',
    textExample: 'What are you doing next <b>week</b>?',
    transcription: '[wiːk]',
    textExampleTranslate: 'Что ты делаешь на следующей неделе?',
    textMeaningTranslate: 'Неделя - это период времени, который длится семь дней',
    wordTranslate: 'неделя',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a2',
    group: 0,
    page: 0,
    word: 'boat',
    image: 'files/01_0005.jpg',
    audio: 'files/01_0005.mp3',
    audioMeaning: 'files/01_0005_meaning.mp3',
    audioExample: 'files/01_0005_example.mp3',
    textMeaning: 'A <i>boat</i> is a vehicle that moves across water.',
    textExample: 'There is a small <b>boat</b> on the lake.',
    transcription: '[bout]',
    textExampleTranslate: 'На озере есть маленькая лодка',
    textMeaningTranslate: 'Лодка - это транспортное средство, которое движется по воде',
    wordTranslate: 'лодка',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a7',
    group: 0,
    page: 0,
    word: 'capital',
    image: 'files/01_0008.jpg',
    audio: 'files/01_0008.mp3',
    audioMeaning: 'files/01_0008_meaning.mp3',
    audioExample: 'files/01_0008_example.mp3',
    textMeaning: 'A <i>capital</i> is a city where a country’s government is based.',
    textExample: 'The <b>capital</b> of the United States is Washington, D.C.',
    transcription: '[kæpətl]',
    textExampleTranslate: 'Столица Соединенных Штатов - Вашингтон, округ Колумбия',
    textMeaningTranslate: 'Столица - это город, в котором базируется правительство страны',
    wordTranslate: 'столица',
  },
  {
    id: '5e9f5ee35eb9e72bc21af6fb',
    group: 1,
    page: 0,
    word: 'flower',
    image: 'files/01_0604.jpg',
    audio: 'files/01_0604.mp3',
    audioMeaning: 'files/01_0604_meaning.mp3',
    audioExample: 'files/01_0604_example.mp3',
    textMeaning: 'A <i>flower</i> is the colored part of a plant.',
    textExample: 'She gave pink <b>flowers</b> to her grandmother.',
    transcription: '[fáuər]',
    textExampleTranslate: 'Она дала розовые цветы своей бабушке',
    textMeaningTranslate: 'Цветок - это цветная часть растения',
    wordTranslate: 'цветок',
  },
  {
    id: '5e9f5ee35eb9e72bc21af6ff',
    group: 1,
    page: 0,
    word: 'million',
    image: 'files/01_0608.jpg',
    audio: 'files/01_0608.mp3',
    audioMeaning: 'files/01_0608_meaning.mp3',
    audioExample: 'files/01_0608_example.mp3',
    textMeaning: 'A <i>million</i> is another way to write the number 1,000,000.',
    textExample: 'Almost 19 <b>million</b> people live in Delhi, India.',
    transcription: '[míljən]',
    textExampleTranslate: 'Почти 19 миллионов человек живут в Дели, Индия',
    textMeaningTranslate: 'Миллион - это еще один способ написать число 1 000 000',
    wordTranslate: 'миллион',
  },
  {
    id: '5e9f5ee35eb9e72bc21af707',
    group: 1,
    page: 0,
    word: 'town',
    image: 'files/01_0616.jpg',
    audio: 'files/01_0616.mp3',
    audioMeaning: 'files/01_0616_meaning.mp3',
    audioExample: 'files/01_0616_example.mp3',
    textMeaning: 'A <i>town</i> is a place where people live and work, and is smaller than a city.',
    textExample: 'I come from a small <b>town</b>, and everyone there knows each other.',
    transcription: '[taun]',
    textExampleTranslate: 'Я из маленького городка, и все там знают друг друга',
    textMeaningTranslate: 'Город - это место, где люди живут и работают, и он меньше города',
    wordTranslate: 'город',
  },
  {
    id: '5e9f5ee35eb9e72bc21af709',
    group: 1,
    page: 0,
    word: 'walk',
    image: 'files/01_0618.jpg',
    audio: 'files/01_0618.mp3',
    audioMeaning: 'files/01_0618_meaning.mp3',
    audioExample: 'files/01_0618_example.mp3',
    textMeaning: 'To <i>walk</i> is to move forward using legs, but it is slower than running.',
    textExample: 'The children <b>walk</b> to school in the morning.',
    transcription: '[wɔːk]',
    textExampleTranslate: 'Дети гуляют в школу по утрам',
    textMeaningTranslate: 'Ходить - значит двигаться вперед, используя ноги, но это медленнее, чем бег',
    wordTranslate: 'ходить',
  },
  {
    id: '5e9f5ee35eb9e72bc21af6fd',
    group: 1,
    page: 0,
    word: 'holiday',
    image: 'files/01_0606.jpg',
    audio: 'files/01_0606.mp3',
    audioMeaning: 'files/01_0606_meaning.mp3',
    audioExample: 'files/01_0606_example.mp3',
    textMeaning: 'A <i>holiday</i> is a special day of celebration.',
    textExample: 'Monday was a <b>holiday</b>, so there was no school or work.',
    transcription: '[hάlədèi]',
    textExampleTranslate: 'Понедельник был выходным, поэтому не было школы или работы',
    textMeaningTranslate: 'Праздник - особый день празднования',
    wordTranslate: 'праздничный день',
  },
  {
    id: '5e9f5ee35eb9e72bc21af702',
    group: 1,
    page: 0,
    word: 'popular',
    image: 'files/01_0611.jpg',
    audio: 'files/01_0611.mp3',
    audioMeaning: 'files/01_0611_meaning.mp3',
    audioExample: 'files/01_0611_example.mp3',
    textMeaning: 'A <i>popular</i> thing is liked by many people.',
    textExample: 'These people are listening to a <b>popular</b> man speak.',
    transcription: '[pάpjulər]',
    textExampleTranslate: 'Эти люди слушают разговор популярного человека',
    textMeaningTranslate: 'Популярная вещь нравится многим людям',
    wordTranslate: 'популярный',
  },
  {
    id: '5e9f5ee35eb9e72bc21af703',
    group: 1,
    page: 0,
    word: 'ski',
    image: 'files/01_0612.jpg',
    audio: 'files/01_0612.mp3',
    audioMeaning: 'files/01_0612_meaning.mp3',
    audioExample: 'files/01_0612_example.mp3',
    textMeaning: 'To <i>ski</i> is to glide on long pieces of wood or metal over snow.',
    textExample: 'The man likes to <b>ski</b> and goes every weekend.',
    transcription: '[skiː]',
    textExampleTranslate: 'Мужчина любит кататься на лыжах и ездит каждые выходные',
    textMeaningTranslate: 'Кататься на лыжах - значит скользить по длинным кускам дерева или металла по снегу',
    wordTranslate: 'лыжи',
  },
  {
    id: '5e9f5ee35eb9e72bc21af70a',
    group: 1,
    page: 0,
    word: 'world',
    image: 'files/01_0620.jpg',
    audio: 'files/01_0620.mp3',
    audioMeaning: 'files/01_0620_meaning.mp3',
    audioExample: 'files/01_0620_example.mp3',
    textMeaning: 'The <i>world</i> is the Earth and all the people and things in it.',
    textExample: 'What are the names of the five oceans of the <b>world</b>?',
    transcription: '[wəːrld]',
    textExampleTranslate: 'Как называются пять океанов мира?',
    textMeaningTranslate: 'Мир - это Земля и все люди и вещи в ней',
    wordTranslate: 'мир',
  },
  {
    id: '5e9f5ee35eb9e72bc21af70b',
    group: 1,
    page: 0,
    word: 'watch',
    image: 'files/01_0619.jpg',
    audio: 'files/01_0619.mp3',
    audioMeaning: 'files/01_0619_meaning.mp3',
    audioExample: 'files/01_0619_example.mp3',
    textMeaning: 'To <i>watch</i> is to look at someone or something for a period of time.',
    textExample: 'My friend came over to <b>watch</b> a movie with me.',
    transcription: '[waʧ]',
    textExampleTranslate: 'Мой друг пришел посмотреть фильм со мной',
    textMeaningTranslate: 'Смотреть - значит смотреть на кого-то или что-то в течение определенного периода времени',
    wordTranslate: 'смотреть',
  },
  {
    id: '5e9f5ee35eb9e72bc21af6fa',
    group: 1,
    page: 0,
    word: 'expensive',
    image: 'files/01_0603.jpg',
    audio: 'files/01_0603.mp3',
    audioMeaning: 'files/01_0603_meaning.mp3',
    audioExample: 'files/01_0603_example.mp3',
    textMeaning: '<i>Expensive</i> things cost a lot of money.',
    textExample: 'My friend drives an <b>expensive</b> sports car.',
    transcription: '[ikspénsiv]',
    textExampleTranslate: 'Мой друг водит дорогой спортивный автомобиль',
    textMeaningTranslate: 'Дорогие вещи стоят больших денег',
    wordTranslate: 'дорогой',
  },
  {
    id: '5e9f5ee35eb9e72bc21af6fc',
    group: 1,
    page: 0,
    word: 'garden',
    image: 'files/01_0605.jpg',
    audio: 'files/01_0605.mp3',
    audioMeaning: 'files/01_0605_meaning.mp3',
    audioExample: 'files/01_0605_example.mp3',
    textMeaning: 'A <i>garden</i> is an area where people grow plants.',
    textExample: 'The <b>garden</b> is very bright and colorful in the spring.',
    transcription: '[gάːrdn]',
    textExampleTranslate: 'Сад очень яркий и красочный весной',
    textMeaningTranslate: 'Сад - это место, где люди выращивают растения',
    wordTranslate: 'сад',
  },
  {
    id: '5e9f5ee35eb9e72bc21af6fe',
    group: 1,
    page: 0,
    word: 'many',
    image: 'files/01_0607.jpg',
    audio: 'files/01_0607.mp3',
    audioMeaning: 'files/01_0607_meaning.mp3',
    audioExample: 'files/01_0607_example.mp3',
    textMeaning: '<i>Many</i> shows that there is a large number of something.',
    textExample: 'There are <b>many</b> people on the street.',
    transcription: '[méni]',
    textExampleTranslate: 'На улице много людей',
    textMeaningTranslate: 'Многие показывают, что есть много чего-то',
    wordTranslate: 'многие',
  },
  {
    id: '5e9f5ee35eb9e72bc21af700',
    group: 1,
    page: 0,
    word: 'mountain',
    image: 'files/01_0609.jpg',
    audio: 'files/01_0609.mp3',
    audioMeaning: 'files/01_0609_meaning.mp3',
    audioExample: 'files/01_0609_example.mp3',
    textMeaning: 'A <i>mountain</i> is a very high hill.',
    textExample: 'Mount Everest is the highest <b>mountain</b> in the world.',
    transcription: '[máuntən]',
    textExampleTranslate: 'Гора Эверест - самая высокая гора в мире',
    textMeaningTranslate: 'Гора - это очень высокий холм',
    wordTranslate: 'гора',
  },
  {
    id: '5e9f5ee35eb9e72bc21af704',
    group: 1,
    page: 0,
    word: 'tower',
    image: 'files/01_0615.jpg',
    audio: 'files/01_0615.mp3',
    audioMeaning: 'files/01_0615_meaning.mp3',
    audioExample: 'files/01_0615_example.mp3',
    textMeaning: 'A <i>tower</i> is a tall, narrow building.',
    textExample: 'This is a very famous <b>tower</b> in Italy.',
    transcription: '[táuər]',
    textExampleTranslate: 'Это очень известная башня в Италии',
    textMeaningTranslate: 'Башня - это высокое узкое здание',
    wordTranslate: 'башня',
  },
  {
    id: '5e9f5ee35eb9e72bc21af705',
    group: 1,
    page: 0,
    word: 'such',
    image: 'files/01_0613.jpg',
    audio: 'files/01_0613.mp3',
    audioMeaning: 'files/01_0613_meaning.mp3',
    audioExample: 'files/01_0613_example.mp3',
    textMeaning: '<i>Such</i> means “like this”.',
    textExample: 'I have never seen <b>such</b> a beautiful sunset before.',
    transcription: '[sʌtʃ]',
    textExampleTranslate: 'Я никогда раньше не видел такой красивый закат',
    textMeaningTranslate: "Такие означает 'как это'",
    wordTranslate: 'такой',
  },
  {
    id: '5e9f5ee35eb9e72bc21af708',
    group: 1,
    page: 0,
    word: 'train',
    image: 'files/01_0617.jpg',
    audio: 'files/01_0617.mp3',
    audioMeaning: 'files/01_0617_meaning.mp3',
    audioExample: 'files/01_0617_example.mp3',
    textMeaning: 'A <i>train</i> is a group of railway cars connected together.',
    textExample: 'The <b>train</b> is very fast, so we can get home in one hour.',
    transcription: '[trein]',
    textExampleTranslate: 'Поезд очень быстрый, поэтому мы можем добраться домой за один час',
    textMeaningTranslate: 'Поезд - это группа железнодорожных вагонов, соединенных вместе',
    wordTranslate: 'поезд',
  },
  {
    id: '5e9f5ee35eb9e72bc21af6f8',
    group: 1,
    page: 0,
    word: 'because',
    image: 'files/01_0601.jpg',
    audio: 'files/01_0601.mp3',
    audioMeaning: 'files/01_0601_meaning.mp3',
    audioExample: 'files/01_0601_example.mp3',
    textMeaning: '<i>Because</i> introduces a reason for something.',
    textExample: 'We need to study <b>because</b> we have a test tomorrow.',
    transcription: '[bikɔ́ːz]',
    textExampleTranslate: 'Нам нужно учиться, потому что завтра у нас тест',
    textMeaningTranslate: 'Потому что вводит причину чего-то',
    wordTranslate: 'потому что',
  },
  {
    id: '5e9f5ee35eb9e72bc21af6f9',
    group: 1,
    page: 0,
    word: 'east',
    image: 'files/01_0602.jpg',
    audio: 'files/01_0602.mp3',
    audioMeaning: 'files/01_0602_meaning.mp3',
    audioExample: 'files/01_0602_example.mp3',
    textMeaning: '<i>East</i> is the direction the sun rises from.',
    textExample: 'My window looks to the <b>east</b>, so I can watch the sunrise every morning.',
    transcription: '[iːst]',
    textExampleTranslate: 'Мое окно смотрит на восток, поэтому я могу наблюдать восход солнца каждое утро',
    textMeaningTranslate: 'Восток - это направление, из которого восходит солнце',
    wordTranslate: 'восток',
  },
  {
    id: '5e9f5ee35eb9e72bc21af701',
    group: 1,
    page: 0,
    word: 'place',
    image: 'files/01_0610.jpg',
    audio: 'files/01_0610.mp3',
    audioMeaning: 'files/01_0610_meaning.mp3',
    audioExample: 'files/01_0610_example.mp3',
    textMeaning: 'A <i>place</i> is a space or area.',
    textExample: 'A library is a <b>place</b> where people can read books.',
    transcription: '[pleis]',
    textExampleTranslate: 'Библиотека - это место, где люди могут читать книги',
    textMeaningTranslate: 'Место - это пространство или область',
    wordTranslate: 'место',
  },
  {
    id: '5e9f5ee35eb9e72bc21af706',
    group: 1,
    page: 0,
    word: 'total',
    image: 'files/01_0614.jpg',
    audio: 'files/01_0614.mp3',
    audioMeaning: 'files/01_0614_meaning.mp3',
    audioExample: 'files/01_0614_example.mp3',
    textMeaning: '<i>Total</i> shows that everyone or everything has been counted.',
    textExample: '.The <b>total</b> cost of the items she bought was $52.',
    transcription: '[tóutl]',
    textExampleTranslate: 'Общая стоимость предметов, которые она купила, составила 52 доллара',
    textMeaningTranslate: 'Всего показывает, что все или все было посчитано',
    wordTranslate: 'всего',
  },
  {
    id: '5e9f5ee35eb9e72bc21af952',
    group: 2,
    page: 0,
    word: 'channel',
    image: 'files/01_1205.jpg',
    audio: 'files/01_1205.mp3',
    audioMeaning: 'files/01_1205_meaning.mp3',
    audioExample: 'files/01_1205_example.mp3',
    textMeaning: 'A <i>channel</i> is a long, deep space between two edges.',
    textExample: 'The river cut a <b>channel</b> through the rocks.',
    transcription: '[ʧǽnl]',
    textExampleTranslate: 'Река пробила канал сквозь скалы',
    textMeaningTranslate: 'Канал - это длинное глубокое пространство между двумя краями',
    wordTranslate: 'канал',
  },
  {
    id: '5e9f5ee35eb9e72bc21af953',
    group: 2,
    page: 0,
    word: 'archaeology',
    image: 'files/01_1203.jpg',
    audio: 'files/01_1203.mp3',
    audioMeaning: 'files/01_1203_meaning.mp3',
    audioExample: 'files/01_1203_example.mp3',
    textMeaning: '<i>Archaeology</i> is the study of the remains left by ancient societies.',
    textExample: 'He enjoyed visiting the Great Pyramids of Egypt because he loves <b>archaeology</b>.',
    transcription: '[ὰːrkiάlədʒi]',
    textExampleTranslate: 'Ему нравилось посещать Великие пирамиды Египта, потому что он любит археологию',
    textMeaningTranslate: 'Археология - это изучение останков, оставленных древними обществами',
    wordTranslate: 'археология',
  },
  {
    id: '5e9f5ee35eb9e72bc21af956',
    group: 2,
    page: 0,
    word: 'corridor',
    image: 'files/01_1207.jpg',
    audio: 'files/01_1207.mp3',
    audioMeaning: 'files/01_1207_meaning.mp3',
    audioExample: 'files/01_1207_example.mp3',
    textMeaning: 'A <i>corridor</i> is a narrow passage that leads into other areas.',
    textExample: 'He took the <b>corridor</b> on the left to go to his office.',
    transcription: '[kɔ́ːridər]',
    textExampleTranslate: 'Он взял коридор слева, чтобы пойти в свой офис',
    textMeaningTranslate: 'Коридор - это узкий проход, ведущий в другие районы',
    wordTranslate: 'коридор',
  },
  {
    id: '5e9f5ee35eb9e72bc21af958',
    group: 2,
    page: 0,
    word: 'elite',
    image: 'files/01_1209.jpg',
    audio: 'files/01_1209.mp3',
    audioMeaning: 'files/01_1209_meaning.mp3',
    audioExample: 'files/01_1209_example.mp3',
    textMeaning: '<i>Elite</i> means of or from a high-level group.',
    textExample: 'Only an <b>elite</b> group was allowed membership into the club.',
    transcription: '[eilíːt]',
    textExampleTranslate: 'Только элитная группа была допущена к членству в клубе',
    textMeaningTranslate: 'Элитные средства из группы высокого уровня',
    wordTranslate: 'элита',
  },
  {
    id: '5e9f5ee35eb9e72bc21af960',
    group: 2,
    page: 0,
    word: 'royal',
    image: 'files/01_1217.jpg',
    audio: 'files/01_1217.mp3',
    audioMeaning: 'files/01_1217_meaning.mp3',
    audioExample: 'files/01_1217_example.mp3',
    textMeaning: '<i>Royal</i> means related to a king or queen.',
    textExample: 'The Duchess was part of the <b>royal</b> family.',
    transcription: '[rɔ́iəl]',
    textExampleTranslate: 'Герцогиня была частью королевской семьи',
    textMeaningTranslate: 'Королевские средства, связанные с королем или королевой',
    wordTranslate: 'королевский',
  },
  {
    id: '5e9f5ee35eb9e72bc21af950',
    group: 2,
    page: 0,
    word: 'acre',
    image: 'files/01_1201.jpg',
    audio: 'files/01_1201.mp3',
    audioMeaning: 'files/01_1201_meaning.mp3',
    audioExample: 'files/01_1201_example.mp3',
    textMeaning: 'An <i>acre</i> is a unit for measuring area.',
    textExample: 'They lived on a 150-<b>acre</b> farm.',
    transcription: '[éikər]',
    textExampleTranslate: 'Они жили на 150-акровой ферме',
    textMeaningTranslate: 'Акр - это единица измерения площади',
    wordTranslate: 'акр',
  },
  {
    id: '5e9f5ee35eb9e72bc21af959',
    group: 2,
    page: 0,
    word: 'engineer',
    image: 'files/01_1210.jpg',
    audio: 'files/01_1210.mp3',
    audioMeaning: 'files/01_1210_meaning.mp3',
    audioExample: 'files/01_1210_example.mp3',
    textMeaning: 'To <i>engineer</i> something is to skillfully plan out how to make that thing.',
    textExample: 'After <b>engineering</b> the robot, they needed to find the correct parts to build it.',
    transcription: '[èndʒiníər]',
    textExampleTranslate: 'После разработки робота им нужно было найти правильные детали для его сборки',
    textMeaningTranslate: 'Инженерно что-то значит умело планировать, как это сделать',
    wordTranslate: 'инженер',
  },
  {
    id: '5e9f5ee35eb9e72bc21af95e',
    group: 2,
    page: 0,
    word: 'lion',
    image: 'files/01_1215.jpg',
    audio: 'files/01_1215.mp3',
    audioMeaning: 'files/01_1215_meaning.mp3',
    audioExample: 'files/01_1215_example.mp3',
    textMeaning: 'A <i>lion</i> is a large animal in the cat family.',
    textExample: 'We went to see the <b>lion</b> at the zoo.',
    transcription: '[láiən]',
    textExampleTranslate: 'Мы пошли, чтобы увидеть льва в зоопарке',
    textMeaningTranslate: 'Лев - большое животное в семье кошек',
    wordTranslate: 'лев',
  },
  {
    id: '5e9f5ee35eb9e72bc21af962',
    group: 2,
    page: 0,
    word: 'stairs',
    image: 'files/01_1219.jpg',
    audio: 'files/01_1219.mp3',
    audioMeaning: 'files/01_1219_meaning.mp3',
    audioExample: 'files/01_1219_example.mp3',
    textMeaning: '<i>Stairs</i> are a set of steps built to go from one level of a building to another.',
    textExample: 'He took the <b>stairs</b> instead of the elevator.',
    transcription: '[stεərz]',
    textExampleTranslate: 'Он поднялся по лестнице вместо лифта',
    textMeaningTranslate:
      'Лестница представляет собой набор ступеней, построенных для перехода с одного уровня здания на другой',
    wordTranslate: 'лестница',
  },
  {
    id: '5e9f5ee35eb9e72bc21af957',
    group: 2,
    page: 0,
    word: 'distinct',
    image: 'files/01_1208.jpg',
    audio: 'files/01_1208.mp3',
    audioMeaning: 'files/01_1208_meaning.mp3',
    audioExample: 'files/01_1208_example.mp3',
    textMeaning: 'A <i>distinct</i> thing is different or stands out.',
    textExample: 'He has a <b>distinct</b> accent.',
    transcription: '[distíŋkt]',
    textExampleTranslate: 'У него отчетливый акцент',
    textMeaningTranslate: 'Отличная вещь отличается или выделяется',
    wordTranslate: 'отличный',
  },
  {
    id: '5e9f5ee35eb9e72bc21af95b',
    group: 2,
    page: 0,
    word: 'gap',
    image: 'files/01_1212.jpg',
    audio: 'files/01_1212.mp3',
    audioMeaning: 'files/01_1212_meaning.mp3',
    audioExample: 'files/01_1212_example.mp3',
    textMeaning: 'A <i>gap</i> is a space between two things.',
    textExample: 'There is a small <b>gap</b> between the blocks of wood.',
    transcription: '[ɡæp]',
    textExampleTranslate: 'Между блоками дерева есть небольшой зазор',
    textMeaningTranslate: 'Разрыв - это пространство между двумя вещами',
    wordTranslate: 'пробел',
  },
  {
    id: '5e9f5ee35eb9e72bc21af95d',
    group: 2,
    page: 0,
    word: 'interior',
    image: 'files/01_1214.jpg',
    audio: 'files/01_1214.mp3',
    audioMeaning: 'files/01_1214_meaning.mp3',
    audioExample: 'files/01_1214_example.mp3',
    textMeaning: 'An <i>interior</i> is the inside of something.',
    textExample: 'They looked at the <b>interior</b> of the box.',
    transcription: '[intíəriər]',
    textExampleTranslate: 'Они посмотрели на внутреннюю часть коробки',
    textMeaningTranslate: 'Интерьер - это что-то внутри',
    wordTranslate: 'интерьер',
  },
  {
    id: '5e9f5ee35eb9e72bc21af95c',
    group: 2,
    page: 0,
    word: 'glory',
    image: 'files/01_1213.jpg',
    audio: 'files/01_1213.mp3',
    audioMeaning: 'files/01_1213_meaning.mp3',
    audioExample: 'files/01_1213_example.mp3',
    textMeaning: '<i>Glory</i> is the importance, magnificence, or specialness of something.',
    textExample: 'They enjoyed the <b>glory</b> of the beautiful sunset.',
    transcription: '[glɔ́ːri]',
    textExampleTranslate: 'Они наслаждались славой прекрасного заката',
    textMeaningTranslate: 'Слава - это важность, великолепие или особенность чего-либо',
    wordTranslate: 'слава',
  },
  {
    id: '5e9f5ee35eb9e72bc21af961',
    group: 2,
    page: 0,
    word: 'sole',
    image: 'files/01_1218.jpg',
    audio: 'files/01_1218.mp3',
    audioMeaning: 'files/01_1218_meaning.mp3',
    audioExample: 'files/01_1218_example.mp3',
    textMeaning: 'A <i>sole</i> person or thing is the only one.',
    textExample: 'She was the <b>sole</b> woman in the room.',
    transcription: '[soul]',
    textExampleTranslate: 'Она была единственной женщиной в комнате',
    textMeaningTranslate: 'Единственный человек или вещь - единственный',
    wordTranslate: 'подошва',
  },
  {
    id: '5e9f5ee35eb9e72bc21af963',
    group: 2,
    page: 0,
    word: 'surface',
    image: 'files/01_1220.jpg',
    audio: 'files/01_1220.mp3',
    audioMeaning: 'files/01_1220_meaning.mp3',
    audioExample: 'files/01_1220_example.mp3',
    textMeaning: 'The <i>surface</i> is the top layer of something.',
    textExample: 'She wiped the <b>surface</b> of the table.',
    transcription: '[sə́ːrfis]',
    textExampleTranslate: 'Она вытерла поверхность стола',
    textMeaningTranslate: 'Поверхность - это верхний слой чего-либо',
    wordTranslate: 'поверхность',
  },
  {
    id: '5e9f5ee35eb9e72bc21af951',
    group: 2,
    page: 0,
    word: 'afterlife',
    image: 'files/01_1202.jpg',
    audio: 'files/01_1202.mp3',
    audioMeaning: 'files/01_1202_meaning.mp3',
    audioExample: 'files/01_1202_example.mp3',
    textMeaning: 'The <i>afterlife</i> is a life that some people believe begins when a person dies.',
    textExample: 'I believe that there is an <b>afterlife</b>.',
    transcription: '[ǽftərlaif]',
    textExampleTranslate: 'Я считаю, что есть загробная жизнь',
    textMeaningTranslate: 'Загробная жизнь - это жизнь, в которую верят некоторые люди, когда человек умирает',
    wordTranslate: 'жизнь после смерти',
  },
  {
    id: '5e9f5ee35eb9e72bc21af954',
    group: 2,
    page: 0,
    word: 'chamber',
    image: 'files/01_1204.jpg',
    audio: 'files/01_1204.mp3',
    audioMeaning: 'files/01_1204_meaning.mp3',
    audioExample: 'files/01_1204_example.mp3',
    textMeaning: 'A <i>chamber</i> is a closed space or room used for a special purpose.',
    textExample: 'The meeting was held in the faculty <b>chamber</b>.',
    transcription: '[ʧéimbər]',
    textExampleTranslate: 'Встреча прошла в факультетской палате',
    textMeaningTranslate: 'Камера - это закрытое пространство или комната, используемая для специальных целей',
    wordTranslate: 'камера',
  },
  {
    id: '5e9f5ee35eb9e72bc21af955',
    group: 2,
    page: 0,
    word: 'core',
    image: 'files/01_1206.jpg',
    audio: 'files/01_1206.mp3',
    audioMeaning: 'files/01_1206_meaning.mp3',
    audioExample: 'files/01_1206_example.mp3',
    textMeaning: 'A <i>core</i> is the main or central part of something.',
    textExample: 'Earth has a solid inner <b>core</b>.',
    transcription: '[kɔːr]',
    textExampleTranslate: 'Земля имеет твердое внутреннее ядро',
    textMeaningTranslate: 'Ядро - это главная или центральная часть чего-либо',
    wordTranslate: 'ядро',
  },
  {
    id: '5e9f5ee35eb9e72bc21af95a',
    group: 2,
    page: 0,
    word: 'found',
    image: 'files/01_1211.jpg',
    audio: 'files/01_1211.mp3',
    audioMeaning: 'files/01_1211_meaning.mp3',
    audioExample: 'files/01_1211_example.mp3',
    textMeaning: 'To <i>found</i> something means to start, organize, or establish that thing.',
    textExample: 'My grandfather <b>founded</b> the City Bank.',
    transcription: '[fə́und]',
    textExampleTranslate: 'Мой дед основал городской банк',
    textMeaningTranslate: 'Найти что-то значит начать, организовать или установить эту вещь',
    wordTranslate: 'нашел',
  },
  {
    id: '5e9f5ee35eb9e72bc21af95f',
    group: 2,
    page: 0,
    word: 'role',
    image: 'files/01_1216.jpg',
    audio: 'files/01_1216.mp3',
    audioMeaning: 'files/01_1216_meaning.mp3',
    audioExample: 'files/01_1216_example.mp3',
    textMeaning: 'A <i>role</i> is a job, position, or part in something.',
    textExample: 'Her <b>role</b> in the office is to sell products to customers.',
    transcription: '[roʊl]',
    textExampleTranslate: 'Ее роль в офисе - продавать товары покупателям',
    textMeaningTranslate: 'Роль - это работа, должность или часть в чем-то',
    wordTranslate: 'роль',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbaa',
    group: 3,
    page: 0,
    word: 'agenda',
    image: 'files/01_1803.jpg',
    audio: 'files/01_1803.mp3',
    audioMeaning: 'files/01_1803_meaning.mp3',
    audioExample: 'files/01_1803_example.mp3',
    textMeaning: 'An <i>agenda</i> is a plan or goal that guides someone’s behavior.',
    textExample: 'The man is pushing his questionable <b>agenda</b> on his colleagues.',
    transcription: '[ədʒéndə]',
    textExampleTranslate: 'Человек выдвигает свою сомнительную повестку дня на своих коллег',
    textMeaningTranslate: 'Повестка дня - это план или цель, определяющая поведение человека',
    wordTranslate: 'повестка дня',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbad',
    group: 3,
    page: 0,
    word: 'depression',
    image: 'files/01_1806.jpg',
    audio: 'files/01_1806.mp3',
    audioMeaning: 'files/01_1806_meaning.mp3',
    audioExample: 'files/01_1806_example.mp3',
    textMeaning: '<i>Depression</i> is a medical condition that makes a person very unhappy for long periods of time.',
    textExample: 'Ron decided to get help for his <b>depression</b>.',
    transcription: '[dipréʃən]',
    textExampleTranslate: 'Рон решил получить помощь от депрессии',
    textMeaningTranslate:
      'Депрессия - это заболевание, которое делает человека очень несчастным в течение длительного времени',
    wordTranslate: 'депрессия',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbaf',
    group: 3,
    page: 0,
    word: 'keyboard',
    image: 'files/01_1809.jpg',
    audio: 'files/01_1809.mp3',
    audioMeaning: 'files/01_1809_meaning.mp3',
    audioExample: 'files/01_1809_example.mp3',
    textMeaning:
      'A <i>keyboard</i> has buttons marked with letters and numbers that are pressed to put information into a computer.',
    textExample: 'Paul spilled coffee all over his <b>keyboard</b>.',
    transcription: '[kíbɔːrd]',
    textExampleTranslate: 'Пол разлил кофе по всей клавиатуре',
    textMeaningTranslate:
      'На клавиатуре есть кнопки, помеченные буквами и цифрами, которые нажимаются для ввода информации в компьютер',
    wordTranslate: 'клавиатура',
  },
  {
    id: '5e9f5ee35eb9e72bc21afba9',
    group: 3,
    page: 0,
    word: 'accountable',
    image: 'files/01_1801.jpg',
    audio: 'files/01_1801.mp3',
    audioMeaning: 'files/01_1801_meaning.mp3',
    audioExample: 'files/01_1801_example.mp3',
    textMeaning: 'When someone is <i>accountable</i>, he or she is responsible for the effects of his or her actions.',
    textExample: 'Political leaders are <b>accountable</b> to the people they represent.',
    transcription: '[əkáuntəbl]',
    textExampleTranslate: 'Политические лидеры ответственны перед людьми, которых они представляют',
    textMeaningTranslate:
      'Когда кто-то несет ответственность, он или она несут ответственность за последствия своих действий',
    wordTranslate: 'подотчетны',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbac',
    group: 3,
    page: 0,
    word: 'correlate',
    image: 'files/01_1805.jpg',
    audio: 'files/01_1805.mp3',
    audioMeaning: 'files/01_1805_meaning.mp3',
    audioExample: 'files/01_1805_example.mp3',
    textMeaning: 'To <i>correlate</i> is to have a close connection to something.',
    textExample: 'Scientists believe that brain size might <b>correlate</b> with intelligence.',
    transcription: '[kɔ́ːrəlèit]',
    textExampleTranslate: 'Ученые считают, что размер мозга может коррелировать с интеллектом',
    textMeaningTranslate: 'Соотносить это значит иметь тесную связь с чем-то',
    wordTranslate: 'коррелят',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbae',
    group: 3,
    page: 0,
    word: 'digital',
    image: 'files/01_1807.jpg',
    audio: 'files/01_1807.mp3',
    audioMeaning: 'files/01_1807_meaning.mp3',
    audioExample: 'files/01_1807_example.mp3',
    textMeaning: 'When something is <i>digital</i>, it is characterized by computer technology.',
    textExample: 'Students prefer to take notes on their laptops and other <b>digital</b> devices.',
    transcription: '[dídʒətl]',
    textExampleTranslate: 'Студенты предпочитают делать заметки на своих ноутбуках и других цифровых устройствах',
    textMeaningTranslate: 'Когда что-то является цифровым, оно характеризуется компьютерными технологиями',
    wordTranslate: 'цифровой',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbb0',
    group: 3,
    page: 0,
    word: 'importance',
    image: 'files/01_1808.jpg',
    audio: 'files/01_1808.mp3',
    audioMeaning: 'files/01_1808_meaning.mp3',
    audioExample: 'files/01_1808_example.mp3',
    textMeaning: '<i>Importance</i> is the quality or state of being important, valuable, or significant.',
    textExample: 'The professor lectured the students on the <b>importance</b> of communication strategies.',
    transcription: '[impɔ́ːrtəns]',
    textExampleTranslate: 'Профессор читал лекции студентам о важности коммуникационных стратегий',
    textMeaningTranslate: 'Важность - это качество или состояние важности, ценности или значимости',
    wordTranslate: 'значение',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbb4',
    group: 3,
    page: 0,
    word: 'presence',
    image: 'files/01_1814.jpg',
    audio: 'files/01_1814.mp3',
    audioMeaning: 'files/01_1814_meaning.mp3',
    audioExample: 'files/01_1814_example.mp3',
    textMeaning: '<i>Presence</i> is when someone or something is present in a particular place.',
    textExample: 'The researcher discovered the <b>presence</b> of bacteria in the water sample.',
    transcription: '[prézns]',
    textExampleTranslate: 'Исследователь обнаружил присутствие бактерий в пробе воды',
    textMeaningTranslate: 'Присутствие - это когда кто-то или что-то присутствует в определенном месте',
    wordTranslate: 'присутствие',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbb6',
    group: 3,
    page: 0,
    word: 'subject',
    image: 'files/01_1815.jpg',
    audio: 'files/01_1815.mp3',
    audioMeaning: 'files/01_1815_meaning.mp3',
    audioExample: 'files/01_1815_example.mp3',
    textMeaning:
      'To <i>subject</i> is to cause or force someone or something to experience something harmful or unpleasant.',
    textExample: 'The location of the trees will <b>subject</b> them to strong winds from the hurricane.',
    transcription: '[sΛbdʒikt]',
    textExampleTranslate: 'Расположение деревьев подвергнет их сильным ветрам от урагана',
    textMeaningTranslate:
      'Субъект должен вызывать или заставлять кого-то или что-либо испытывать что-то вредное или неприятное',
    wordTranslate: 'тема',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbbb',
    group: 3,
    page: 0,
    word: 'trend',
    image: 'files/01_1819.jpg',
    audio: 'files/01_1819.mp3',
    audioMeaning: 'files/01_1819_meaning.mp3',
    audioExample: 'files/01_1819_example.mp3',
    textMeaning: 'A <i>trend</i> is a general tendency in the way a situation is changing or developing.',
    textExample: 'Lucy likes to think she started this fashion <b>trend</b>.',
    transcription: '[trend]',
    textExampleTranslate: 'Люси нравится думать, что она начала эту модную тенденцию',
    textMeaningTranslate: 'Тенденция - это общая тенденция изменения или развития ситуации',
    wordTranslate: 'тренд',
  },
  {
    id: '5e9f5ee35eb9e72bc21afba8',
    group: 3,
    page: 0,
    word: 'addictive',
    image: 'files/01_1802.jpg',
    audio: 'files/01_1802.mp3',
    audioMeaning: 'files/01_1802_meaning.mp3',
    audioExample: 'files/01_1802_example.mp3',
    textMeaning: 'If something is <i>addictive</i>, it is hard to stop doing.',
    textExample: 'I think this game is very <b>addictive</b>.',
    transcription: '[ədíktiv]',
    textExampleTranslate: 'Я думаю, что эта игра очень затягивает',
    textMeaningTranslate: 'Если что-то вызывает привыкание, трудно перестать делать',
    wordTranslate: 'привыкание',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbb2',
    group: 3,
    page: 0,
    word: 'media',
    image: 'files/01_1811.jpg',
    audio: 'files/01_1811.mp3',
    audioMeaning: 'files/01_1811_meaning.mp3',
    audioExample: 'files/01_1811_example.mp3',
    textMeaning: '<i>Media</i> is the different ways of entertaining and giving information to the public.',
    textExample: 'Many people like to express their opinions online using social <b>media</b>.',
    transcription: '[míːdiə]',
    textExampleTranslate: 'Многие люди хотели бы выразить свое мнение в Интернете с помощью социальных сетей',
    textMeaningTranslate: 'СМИ - это разные способы развлечения и предоставления информации общественности',
    wordTranslate: 'CМИ',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbb1',
    group: 3,
    page: 0,
    word: 'loneliness',
    image: 'files/01_1810.jpg',
    audio: 'files/01_1810.mp3',
    audioMeaning: 'files/01_1810_meaning.mp3',
    audioExample: 'files/01_1810_example.mp3',
    textMeaning: '<i>Loneliness</i> is the unhappiness that is felt by someone if they do not have any friends.',
    textExample: 'Many people join social clubs to escape <b>loneliness</b>.',
    transcription: '[lóunlinis]',
    textExampleTranslate: 'Многие люди вступают в социальные клубы, чтобы избежать одиночества',
    textMeaningTranslate: 'Одиночество - это несчастье, которое кто-то чувствует, если у него нет друзей',
    wordTranslate: 'одиночество',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbba',
    group: 3,
    page: 0,
    word: 'validate',
    image: 'files/01_1820.jpg',
    audio: 'files/01_1820.mp3',
    audioMeaning: 'files/01_1820_meaning.mp3',
    audioExample: 'files/01_1820_example.mp3',
    textMeaning: 'To <i>validate</i> is to make someone feel that his or her ideas and feelings are respected.',
    textExample: 'Winning first prize will <b>validate</b> all of Tony’s hard work.',
    transcription: '[vǽlədèit]',
    textExampleTranslate: 'Получение первого приза подтвердит всю тяжелую работу Тони',
    textMeaningTranslate: 'Подтвердить - значит заставить кого-то почувствовать, что его или ее идеи и чувства уважают',
    wordTranslate: 'проверка',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbb8',
    group: 3,
    page: 0,
    word: 'survey',
    image: 'files/01_1817.jpg',
    audio: 'files/01_1817.mp3',
    audioMeaning: 'files/01_1817_meaning.mp3',
    audioExample: 'files/01_1817_example.mp3',
    textMeaning:
      'A <i>survey</i> is a set of questions that are asked to a large number of people in order to find out about opinions.',
    textExample: 'I filled out a <b>survey</b> about my shopping experience at the department store.',
    transcription: '[sərvéi]',
    textExampleTranslate: 'Я заполнил опрос о моем опыте покупок в универмаге',
    textMeaningTranslate:
      'Опрос - это набор вопросов, которые задают большому количеству людей, чтобы узнать о мнениях',
    wordTranslate: 'опрос',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbab',
    group: 3,
    page: 0,
    word: 'coin',
    image: 'files/01_1804.jpg',
    audio: 'files/01_1804.mp3',
    audioMeaning: 'files/01_1804_meaning.mp3',
    audioExample: 'files/01_1804_example.mp3',
    textMeaning: 'To <i>coin</i> is to create a new word or phrase that other people begin to use.',
    textExample: 'The coach <b>coined</b> the phrase, “There is no ‘I’ in team.”',
    transcription: '[kɔin]',
    textExampleTranslate: "Тренер придумал фразу 'В команде нет 'я''",
    textMeaningTranslate: 'Монета означает создание нового слова или фразы, которые начинают использовать другие люди',
    wordTranslate: 'монета',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbb3',
    group: 3,
    page: 0,
    word: 'platform',
    image: 'files/01_1812.jpg',
    audio: 'files/01_1812.mp3',
    audioMeaning: 'files/01_1812_meaning.mp3',
    audioExample: 'files/01_1812_example.mp3',
    textMeaning:
      'A <i>platform</i> is something that allows someone to tell a large number of people about an idea, product, etc.',
    textExample: 'The band uses their music as a <b>platform</b> to express their political beliefs.',
    transcription: '[plǽtfɔːrm]',
    textExampleTranslate:
      'Группа использует свою музыку в качестве платформы для выражения своих политических убеждений',
    textMeaningTranslate:
      'Платформа - это то, что позволяет кому-то рассказать большому количеству людей об идее, продукте и т. Д',
    wordTranslate: 'платформа',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbb5',
    group: 3,
    page: 0,
    word: 'poor',
    image: 'files/01_1813.jpg',
    audio: 'files/01_1813.mp3',
    audioMeaning: 'files/01_1813_meaning.mp3',
    audioExample: 'files/01_1813_example.mp3',
    textMeaning: 'When something is <i>poor</i>, it is not as good as it could or should be.',
    textExample: 'The condition of the sidewalk is very <b>poor</b>.',
    transcription: '[puər]',
    textExampleTranslate: 'Состояние тротуара очень плохое',
    textMeaningTranslate: 'Когда что-то плохое, это не так хорошо, как могло бы или должно быть',
    wordTranslate: 'бедных',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbb7',
    group: 3,
    page: 0,
    word: 'surge',
    image: 'files/01_1816.jpg',
    audio: 'files/01_1816.mp3',
    audioMeaning: 'files/01_1816_meaning.mp3',
    audioExample: 'files/01_1816_example.mp3',
    textMeaning: 'A <i>surge</i> is a sudden, large increase in something.',
    textExample: 'All at once, there was a <b>surge</b> of runners at the finish line.',
    transcription: '[səːrdʒ]',
    textExampleTranslate: 'Внезапно на финише всплеск бегунов',
    textMeaningTranslate: 'Волна - это внезапное, значительное увеличение чего-либо',
    wordTranslate: 'всплеск',
  },
  {
    id: '5e9f5ee35eb9e72bc21afbb9',
    group: 3,
    page: 0,
    word: 'target',
    image: 'files/01_1818.jpg',
    audio: 'files/01_1818.mp3',
    audioMeaning: 'files/01_1818_meaning.mp3',
    audioExample: 'files/01_1818_example.mp3',
    textMeaning: 'To <i>target</i> is to aim an attack at someone or something.',
    textExample: 'Scientists are looking for new drugs to <b>target</b> cancer cells.',
    transcription: '[tάːrgit]',
    textExampleTranslate: 'Ученые ищут новые лекарства для нацеливания на раковые клетки',
    textMeaningTranslate: 'Таргетировать это нацеливать нападение на кого-то или что-то',
    wordTranslate: 'мишень',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe01',
    group: 4,
    page: 0,
    word: 'beverage',
    image: 'files/01_2402.jpg',
    audio: 'files/01_2402.mp3',
    audioMeaning: 'files/01_2402_meaning.mp3',
    audioExample: 'files/01_2402_example.mp3',
    textMeaning: 'A <i>beverage</i> is a drink.',
    textExample: 'The waiter brought our <b>beverages</b> first. Then he brought our food.',
    transcription: '[bévəridʒ]',
    textExampleTranslate: 'Сначала официант принес наши напитки. Затем он принес нашу еду',
    textMeaningTranslate: 'Напиток - это то, что пьют',
    wordTranslate: 'напиток',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe10',
    group: 4,
    page: 0,
    word: 'subtle',
    image: 'files/01_2417.jpg',
    audio: 'files/01_2417.mp3',
    audioMeaning: 'files/01_2417_meaning.mp3',
    audioExample: 'files/01_2417_example.mp3',
    textMeaning: 'When something is <i>subtle</i>, it is not easy to see or notice.',
    textExample: 'The handsome man has a <b>subtle</b> smile.',
    transcription: '[sʌ́tl]',
    textExampleTranslate: 'У красавца тонкая улыбка',
    textMeaningTranslate: 'Когда что-то тонкое, это не так легко увидеть или заметить',
    wordTranslate: 'тонкий',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe06',
    group: 4,
    page: 0,
    word: 'cultivate',
    image: 'files/01_2407.jpg',
    audio: 'files/01_2407.mp3',
    audioMeaning: 'files/01_2407_meaning.mp3',
    audioExample: 'files/01_2407_example.mp3',
    textMeaning: 'To <i>cultivate</i> plants is to care for them and help them grow.',
    textExample: 'A research company is <b>cultivating</b> new kinds of rice to aid poor countries.',
    transcription: '[kʌ́ltəvèit]',
    textExampleTranslate: 'Исследовательская компания выращивает новые виды риса, чтобы помочь бедным странам',
    textMeaningTranslate: 'Выращивать растения - значит заботиться о них и помогать им расти',
    wordTranslate: 'культивировать',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe05',
    group: 4,
    page: 0,
    word: 'contemporary',
    image: 'files/01_2406.jpg',
    audio: 'files/01_2406.mp3',
    audioMeaning: 'files/01_2406_meaning.mp3',
    audioExample: 'files/01_2406_example.mp3',
    textMeaning: 'When something is <i>contemporary</i>, it is related to the present time.',
    textExample: '<b>Contemporary</b> scientists have learned quite a bit about DNA.',
    transcription: '[kəntémpərèri]',
    textExampleTranslate: 'Современные ученые узнали совсем немного о ДНК',
    textMeaningTranslate: 'Когда что-то современно, оно связано с настоящим временем',
    wordTranslate: 'современный',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe08',
    group: 4,
    page: 0,
    word: 'odor',
    image: 'files/01_2410.jpg',
    audio: 'files/01_2410.mp3',
    audioMeaning: 'files/01_2410_meaning.mp3',
    audioExample: 'files/01_2410_example.mp3',
    textMeaning: 'An <i>odor</i> is a very distinct smell.',
    textExample: 'He knew there was a leak when he noticed the strong <b>odor</b> of natural gas.',
    transcription: '[óudər]',
    textExampleTranslate: 'Он знал, что произошла утечка, когда заметил сильный запах природного газа',
    textMeaningTranslate: 'Запах очень отчетливый запах',
    wordTranslate: 'запах',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe0c',
    group: 4,
    page: 0,
    word: 'plantation',
    image: 'files/01_2413.jpg',
    audio: 'files/01_2413.mp3',
    audioMeaning: 'files/01_2413_meaning.mp3',
    audioExample: 'files/01_2413_example.mp3',
    textMeaning: 'A <i>plantation</i> is a big farm that only grows certain kinds of crops.',
    textExample: 'In the 1800s, there were many cotton <b>plantations</b> in the southern US.',
    transcription: '[plæntéiʃən]',
    textExampleTranslate: 'В 1800-х годах на юге США было много хлопковых плантаций',
    textMeaningTranslate: 'Плантация - это большая ферма, которая выращивает только определенные виды культур',
    wordTranslate: 'плантация',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe0b',
    group: 4,
    page: 0,
    word: 'paradise',
    image: 'files/01_2412.jpg',
    audio: 'files/01_2412.mp3',
    audioMeaning: 'files/01_2412_meaning.mp3',
    audioExample: 'files/01_2412_example.mp3',
    textMeaning: '<i>Paradise</i> is the place or condition of happiness where things are perfect.',
    textExample: 'My vacation in Hawaii was like being in <b>paradise</b>.',
    transcription: '[pǽrədàis]',
    textExampleTranslate: 'Мой отпуск на Гавайях был как в раю',
    textMeaningTranslate: 'Рай - это место или состояние счастья, где все идеально',
    wordTranslate: 'рай',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe0e',
    group: 4,
    page: 0,
    word: 'rate',
    image: 'files/01_2415.jpg',
    audio: 'files/01_2415.mp3',
    audioMeaning: 'files/01_2415_meaning.mp3',
    audioExample: 'files/01_2415_example.mp3',
    textMeaning: 'A <i>rate</i> is the speed at which something happens.',
    textExample: 'Grass tends to grow at a very slow <b>rate</b>.',
    transcription: '[reit]',
    textExampleTranslate: 'Трава имеет тенденцию расти очень медленно',
    textMeaningTranslate: 'Скорость - это скорость, с которой что-то происходит',
    wordTranslate: 'ставка',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe11',
    group: 4,
    page: 0,
    word: 'texture',
    image: 'files/01_2418.jpg',
    audio: 'files/01_2418.mp3',
    audioMeaning: 'files/01_2418_meaning.mp3',
    audioExample: 'files/01_2418_example.mp3',
    textMeaning: 'The <i>texture</i> of something is the way its surface looks and feels.',
    textExample: 'The <b>texture</b> of a rock found in the water is typically very smooth.',
    transcription: '[téksʧər]',
    textExampleTranslate: 'Текстура камня, найденного в воде, обычно очень гладкая',
    textMeaningTranslate: 'Текстура чего-то - это то, как его поверхность выглядит и ощущается',
    wordTranslate: 'текстура',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe00',
    group: 4,
    page: 0,
    word: 'aroma',
    image: 'files/01_2401.jpg',
    audio: 'files/01_2401.mp3',
    audioMeaning: 'files/01_2401_meaning.mp3',
    audioExample: 'files/01_2401_example.mp3',
    textMeaning: 'An <i>aroma</i> is a scent or smell.',
    textExample: 'I love the <b>aroma</b> of coffee in the morning.',
    transcription: '[əróumə]',
    textExampleTranslate: 'Я люблю аромат кофе по утрам',
    textMeaningTranslate: 'Аромат - это запах или благоухание',
    wordTranslate: 'аромат',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe03',
    group: 4,
    page: 0,
    word: 'cluster',
    image: 'files/01_2403.jpg',
    audio: 'files/01_2403.mp3',
    audioMeaning: 'files/01_2403_meaning.mp3',
    audioExample: 'files/01_2403_example.mp3',
    textMeaning: 'A <i>cluster</i> of things is a small group of them placed close together.',
    textExample: 'She held a large <b>cluster</b> of grapes in her hand.',
    transcription: '[klʌ́stər]',
    textExampleTranslate: 'Она держала в руке большую гроздь винограда',
    textMeaningTranslate: 'Кластер вещей - это небольшая группа, расположенная близко друг к другу',
    wordTranslate: 'кластер',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe09',
    group: 4,
    page: 0,
    word: 'humid',
    image: 'files/01_2409.jpg',
    audio: 'files/01_2409.mp3',
    audioMeaning: 'files/01_2409_meaning.mp3',
    audioExample: 'files/01_2409_example.mp3',
    textMeaning: 'When it is <i>humid</i>, there is a lot of water in the air.',
    textExample: 'It is very <b>humid</b> inside a sauna.',
    transcription: '[hjúːmid]',
    textExampleTranslate: 'В сауне очень влажно',
    textMeaningTranslate: 'Когда влажно, в воздухе много воды',
    wordTranslate: 'влажный',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe0d',
    group: 4,
    page: 0,
    word: 'rapid',
    image: 'files/01_2414.jpg',
    audio: 'files/01_2414.mp3',
    audioMeaning: 'files/01_2414_meaning.mp3',
    audioExample: 'files/01_2414_example.mp3',
    textMeaning: 'When something is <i>rapid</i>, it moves or changes very quickly.',
    textExample: 'His mother was surprised by her son’s <b>rapid</b> growth.',
    transcription: '[rǽpid]',
    textExampleTranslate: 'Его мать была удивлена быстрым ростом ее сына',
    textMeaningTranslate: 'Когда что-то быстрое, оно движется или меняется очень быстро',
    wordTranslate: 'быстрый',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe0f',
    group: 4,
    page: 0,
    word: 'soothing',
    image: 'files/01_2416.jpg',
    audio: 'files/01_2416.mp3',
    audioMeaning: 'files/01_2416_meaning.mp3',
    audioExample: 'files/01_2416_example.mp3',
    textMeaning: 'When something is <i>soothing</i>, it makes you calm or relaxed.',
    textExample: 'The <b>soothing</b> music helped the baby fall asleep.',
    transcription: '[súːðiŋ]',
    textExampleTranslate: 'Успокаивающая музыка помогла ребенку уснуть',
    textMeaningTranslate: 'Когда что-то успокаивает, это успокаивает или расслабляет',
    wordTranslate: 'успокаивать',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe13',
    group: 4,
    page: 0,
    word: 'vary',
    image: 'files/01_2420.jpg',
    audio: 'files/01_2420.mp3',
    audioMeaning: 'files/01_2420_meaning.mp3',
    audioExample: 'files/01_2420_example.mp3',
    textMeaning: 'To <i>vary</i> means to be different from another thing in size or amount.',
    textExample: 'The heights of the people in my class <b>vary</b> by a large amount.',
    transcription: '[vɛə́ri]',
    textExampleTranslate: 'Высота людей в моем классе сильно варьируется',
    textMeaningTranslate: 'Различаться означает отличаться от другой вещи по размеру или количеству',
    wordTranslate: 'изменяется',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe02',
    group: 4,
    page: 0,
    word: 'combine',
    image: 'files/01_2404.jpg',
    audio: 'files/01_2404.mp3',
    audioMeaning: 'files/01_2404_meaning.mp3',
    audioExample: 'files/01_2404_example.mp3',
    textMeaning: 'To <i>combine</i> is to join together to make a single thing or group.',
    textExample: 'Mina <b>combined</b> peanut butter and jelly to make a sandwich.',
    transcription: '[kəmbáin]',
    textExampleTranslate: 'Мина объединила арахисовое масло и желе, чтобы сделать бутерброд',
    textMeaningTranslate: 'Объединить - значит объединиться, чтобы создать одну вещь или группу',
    wordTranslate: 'объединить',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe04',
    group: 4,
    page: 0,
    word: 'condensed',
    image: 'files/01_2405.jpg',
    audio: 'files/01_2405.mp3',
    audioMeaning: 'files/01_2405_meaning.mp3',
    audioExample: 'files/01_2405_example.mp3',
    textMeaning: 'When a liquid is <i>condensed</i>, it is made thicker.',
    textExample: 'One way to make a dessert thick and sweet is to use <b>condensed</b> milk.',
    transcription: '[kəndénst]',
    textExampleTranslate: 'Один из способов сделать десерт густым и сладким - использовать сгущенное молоко',
    textMeaningTranslate: 'Когда жидкость конденсируется, она становится гуще',
    wordTranslate: 'сгущенное',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe07',
    group: 4,
    page: 0,
    word: 'divine',
    image: 'files/01_2408.jpg',
    audio: 'files/01_2408.mp3',
    audioMeaning: 'files/01_2408_meaning.mp3',
    audioExample: 'files/01_2408_example.mp3',
    textMeaning: 'When something is <i>divine</i>, it is related to gods.',
    textExample: 'Legends say that music was given to humans as a <b>divine</b> gift from the gods.',
    transcription: '[diváin]',
    textExampleTranslate: 'Легенды говорят, что музыка была дана людям как божественный дар от богов',
    textMeaningTranslate: 'Когда что-то божественное, это связано с богами',
    wordTranslate: 'божественный',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe0a',
    group: 4,
    page: 0,
    word: 'palate',
    image: 'files/01_2411.jpg',
    audio: 'files/01_2411.mp3',
    audioMeaning: 'files/01_2411_meaning.mp3',
    audioExample: 'files/01_2411_example.mp3',
    textMeaning: 'The <i>palate</i> is the top part of the mouth.',
    textExample: 'You can touch your <b>palate</b> with your tongue.',
    transcription: '[pǽlit]',
    textExampleTranslate: 'Вы можете коснуться своего неба своим языком',
    textMeaningTranslate: 'Небо - это верхняя часть рта',
    wordTranslate: 'небо',
  },
  {
    id: '5e9f5ee35eb9e72bc21afe12',
    group: 4,
    page: 0,
    word: 'toxic',
    image: 'files/01_2419.jpg',
    audio: 'files/01_2419.mp3',
    audioMeaning: 'files/01_2419_meaning.mp3',
    audioExample: 'files/01_2419_example.mp3',
    textMeaning: 'When something is <i>toxic</i>, it is poisonous and very dangerous.',
    textExample: 'Please check the label to see if the product is <b>toxic</b>.',
    transcription: '[tɑ́ksik]',
    textExampleTranslate: 'Пожалуйста, проверьте этикетку, чтобы увидеть, является ли продукт токсичным',
    textMeaningTranslate: 'Когда что-то токсично, оно ядовито и очень опасно',
    wordTranslate: 'токсичный',
  },
  {
    id: '5e9f5ee35eb9e72bc21b0058',
    group: 5,
    page: 0,
    word: 'adverse',
    image: 'files/01_3001.jpg',
    audio: 'files/01_3001.mp3',
    audioMeaning: 'files/01_3001_meaning.mp3',
    audioExample: 'files/01_3001_example.mp3',
    textMeaning: 'Something that has an <i>adverse</i> effect can be harmful, dangerous, or unfavorable.',
    textExample: 'I worry that the tornado will have an <b>adverse</b> effect on the farm.',
    transcription: '[ædvɜːrs]',
    textExampleTranslate: 'Я беспокоюсь, что торнадо окажет неблагоприятное влияние на ферму',
    textMeaningTranslate:
      'То, что оказывает неблагоприятное воздействие, может быть вредным, опасным или неблагоприятным',
    wordTranslate: 'неблагоприятный',
  },
  {
    id: '5e9f5ee35eb9e72bc21b0059',
    group: 5,
    page: 0,
    word: 'alternate',
    image: 'files/01_3002.jpg',
    audio: 'files/01_3002.mp3',
    audioMeaning: 'files/01_3002_meaning.mp3',
    audioExample: 'files/01_3002_example.mp3',
    textMeaning: 'An <i>alternate</i> option is a different option.',
    textExample: 'Taking the bus and driving to work are <b>alternate</b> ways to travel.',
    transcription: '[ɔ́ːltərnət]',
    textExampleTranslate: 'Поездка на автобусе и езда на работу - альтернативные способы передвижения',
    textMeaningTranslate: 'Альтернативный вариант - это другой вариант',
    wordTranslate: 'альтернативный',
  },
  {
    id: '5e9f5ee35eb9e72bc21b005d',
    group: 5,
    page: 0,
    word: 'discard',
    image: 'files/01_3007.jpg',
    audio: 'files/01_3007.mp3',
    audioMeaning: 'files/01_3007_meaning.mp3',
    audioExample: 'files/01_3007_example.mp3',
    textMeaning: 'To <i>discard</i> something is to throw it away.',
    textExample: 'After repairing the window, <b>discard</b> any broken glass.',
    transcription: '[diskάːrd]',
    textExampleTranslate: 'После ремонта окна откажитесь от разбитого стекла',
    textMeaningTranslate: 'Отбросить что-то - значит выбросить',
    wordTranslate: 'отбрасывание',
  },
  {
    id: '5e9f5ee35eb9e72bc21b0060',
    group: 5,
    page: 0,
    word: 'ecologically',
    image: 'files/01_3009.jpg',
    audio: 'files/01_3009.mp3',
    audioMeaning: 'files/01_3009_meaning.mp3',
    audioExample: 'files/01_3009_example.mp3',
    textMeaning:
      '<i>Ecologically</i> means that something is done in a way that concerns living organisms and the environment.',
    textExample: 'We planted our garden according to <b>ecologically</b> correct practices.',
    transcription: '[èkəlάdʒikəli]',
    textExampleTranslate: 'Мы посадили наш сад в соответствии с экологически правильными методами',
    textMeaningTranslate:
      'Экологически означает, что что-то сделано таким образом, что касается живых организмов и окружающей среды',
    wordTranslate: 'экологически',
  },
  {
    id: '5e9f5ee35eb9e72bc21b0067',
    group: 5,
    page: 0,
    word: 'reusable',
    image: 'files/01_3016.jpg',
    audio: 'files/01_3016.mp3',
    audioMeaning: 'files/01_3016_meaning.mp3',
    audioExample: 'files/01_3016_example.mp3',
    textMeaning: 'An object that is <i>reusable</i> can be utilized over and over again.',
    textExample: 'Saburo keeps his empty jelly jars because they are <b>reusable</b> for storing sewing supplies.',
    transcription: '[riúzəbl]',
    textExampleTranslate:
      'Сабуро хранит свои пустые желейные банки, потому что их можно использовать для хранения швейных принадлежностей',
    textMeaningTranslate: 'Объект, который можно использовать повторно, можно использовать снова и снова',
    wordTranslate: 'многоразового использования',
  },
  {
    id: '5e9f5ee35eb9e72bc21b0068',
    group: 5,
    page: 0,
    word: 'stuffed',
    image: 'files/01_3017.jpg',
    audio: 'files/01_3017.mp3',
    audioMeaning: 'files/01_3017_meaning.mp3',
    audioExample: 'files/01_3017_example.mp3',
    textMeaning: 'When something is <i>stuffed</i>, it is pushed into a small space.',
    textExample: 'The newspapers were all <b>stuffed</b> into the drawer.',
    transcription: '[stʌft]',
    textExampleTranslate: 'Все газеты были спрятаны в ящик',
    textMeaningTranslate: 'Когда что-то наполняется, оно выталкивается в небольшое пространство',
    wordTranslate: 'чучела',
  },
  {
    id: '5e9f5ee35eb9e72bc21b0069',
    group: 5,
    page: 0,
    word: 'tragic',
    image: 'files/01_3018.jpg',
    audio: 'files/01_3018.mp3',
    audioMeaning: 'files/01_3018_meaning.mp3',
    audioExample: 'files/01_3018_example.mp3',
    textMeaning: 'A <i>tragic</i> event causes sadness because it might involve death or suffering.',
    textExample: 'The entire community attended the memorial service for the victims of the <b>tragic</b> fire.',
    transcription: '[trǽdʒik]',
    textExampleTranslate: 'Вся община посетила панихиду по жертвам трагического пожара',
    textMeaningTranslate:
      'Трагическое событие вызывает грусть, потому что оно может повлечь за собой смерть или страдание',
    wordTranslate: 'трагическое',
  },
  {
    id: '5e9f5ee35eb9e72bc21b005b',
    group: 5,
    page: 0,
    word: 'boxed',
    image: 'files/01_3004.jpg',
    audio: 'files/01_3004.mp3',
    audioMeaning: 'files/01_3004_meaning.mp3',
    audioExample: 'files/01_3004_example.mp3',
    textMeaning: 'When something is <i>boxed</i>, it is inside a package.',
    textExample: 'Justine brought a <b>boxed</b> gift to the birthday party.',
    transcription: '[bakst]',
    textExampleTranslate: 'Джастин принесла коробочный подарок на день рождения',
    textMeaningTranslate: 'Когда что-то упаковано, оно внутри упаковки',
    wordTranslate: 'боксовый',
  },
  {
    id: '5e9f5ee35eb9e72bc21b0061',
    group: 5,
    page: 0,
    word: 'fatal',
    image: 'files/01_3010.jpg',
    audio: 'files/01_3010.mp3',
    audioMeaning: 'files/01_3010_meaning.mp3',
    audioExample: 'files/01_3010_example.mp3',
    textMeaning: 'Something that is <i>fatal</i> results in someone’s death.',
    textExample: 'Being shot by the attacker proved <b>fatal</b> to the victim.',
    transcription: '[féitl]',
    textExampleTranslate: 'Застрелен нападавшим оказался смертельным для жертвы',
    textMeaningTranslate: 'Нечто смертельное приводит к чьей-то смерти',
    wordTranslate: 'фатальным',
  },
  {
    id: '5e9f5ee35eb9e72bc21b0064',
    group: 5,
    page: 0,
    word: 'overuse',
    image: 'files/01_3013.jpg',
    audio: 'files/01_3013.mp3',
    audioMeaning: 'files/01_3013_meaning.mp3',
    audioExample: 'files/01_3013_example.mp3',
    textMeaning: '<i>Overuse</i> occurs when something is utilized too many times.',
    textExample: 'Rochelle’s <b>overuse</b> of the exercise bike caused the gears to break.',
    transcription: '[òuvərjúːz]',
    textExampleTranslate: 'Чрезмерное использование Рошель велотренажера вызвало поломку передач',
    textMeaningTranslate: 'Чрезмерное использование происходит, когда что-то используется слишком много раз',
    wordTranslate: 'злоупотребляют',
  },
  {
    id: '5e9f5ee35eb9e72bc21b0066',
    group: 5,
    page: 0,
    word: 'recycle',
    image: 'files/01_3015.jpg',
    audio: 'files/01_3015.mp3',
    audioMeaning: 'files/01_3015_meaning.mp3',
    audioExample: 'files/01_3015_example.mp3',
    textMeaning: 'When you <i>recycle</i> an object, you use its parts to make something else.',
    textExample: 'We <b>recycle</b> our newspapers so that they can be made into packing boxes.',
    transcription: '[riúzəbl]',
    textExampleTranslate: 'Мы перерабатываем наши газеты, чтобы они могли быть превращены в упаковочные коробки',
    textMeaningTranslate: 'Когда вы перерабатываете объект, вы используете его части, чтобы сделать что-то еще',
    wordTranslate: 'рециркулировать',
  },
  {
    id: '5e9f5ee35eb9e72bc21b0065',
    group: 5,
    page: 0,
    word: 'pond',
    image: 'files/01_3014.jpg',
    audio: 'files/01_3014.mp3',
    audioMeaning: 'files/01_3014_meaning.mp3',
    audioExample: 'files/01_3014_example.mp3',
    textMeaning: 'A <i>pond</i> is a freshwater body that is smaller than a lake.',
    textExample: 'I learned to swim at the <b>pond</b> behind the recreation center.',
    transcription: '[pand]',
    textExampleTranslate: 'Я научился плавать на пруду за базой отдыха',
    textMeaningTranslate: 'Пруд - это пресноводное тело, которое меньше озера',
    wordTranslate: 'пруд',
  },
  {
    id: '5e9f5ee35eb9e72bc21b005c',
    group: 5,
    page: 0,
    word: 'choke',
    image: 'files/01_3005.jpg',
    audio: 'files/01_3005.mp3',
    audioMeaning: 'files/01_3005_meaning.mp3',
    audioExample: 'files/01_3005_example.mp3',
    textMeaning: 'If you <i>choke</i> on something, it stops you from breathing.',
    textExample: 'The gum Malinda swallowed made her <b>choke</b>.',
    transcription: '[ʧouk]',
    textExampleTranslate: 'Жвачка, которую Малинда проглотила, заставила ее задохнуться',
    textMeaningTranslate: 'Если вы задыхаетесь, это мешает вам дышать',
    wordTranslate: 'удушение',
  },
  {
    id: '5e9f5ee35eb9e72bc21b005a',
    group: 5,
    page: 0,
    word: 'biodegradable',
    image: 'files/01_3003.jpg',
    audio: 'files/01_3003.mp3',
    audioMeaning: 'files/01_3003_meaning.mp3',
    audioExample: 'files/01_3003_example.mp3',
    textMeaning:
      'Materials that are <i>biodegradable</i> break down naturally into substances that do not harm the environment.',
    textExample: 'I use <b>biodegradable</b> compost to feed my garden.',
    transcription: '[bàioudigréidəbl]',
    textExampleTranslate: 'Я использую биоразлагаемый компост, чтобы кормить свой сад',
    textMeaningTranslate:
      'Биоразлагаемые материалы естественным образом распадаются на вещества, которые не наносят вреда окружающей среде',
    wordTranslate: 'биоразлагаемый',
  },
  {
    id: '5e9f5ee35eb9e72bc21b005e',
    group: 5,
    page: 0,
    word: 'convenient',
    image: 'files/01_3006.jpg',
    audio: 'files/01_3006.mp3',
    audioMeaning: 'files/01_3006_meaning.mp3',
    audioExample: 'files/01_3006_example.mp3',
    textMeaning: 'When something is <i>convenient</i>, it saves you time or effort.',
    textExample: 'Walking through the park is a <b>convenient</b> way to exercise on the way to work.',
    transcription: '[kənvíːnjənt]',
    textExampleTranslate: 'Прогулка по парку - это удобный способ тренировки по дороге на работу',
    textMeaningTranslate: 'Когда что-то удобно, это экономит ваше время или усилия',
    wordTranslate: 'удобный',
  },
  {
    id: '5e9f5ee35eb9e72bc21b0063',
    group: 5,
    page: 0,
    word: 'municipal',
    image: 'files/01_3012.jpg',
    audio: 'files/01_3012.mp3',
    audioMeaning: 'files/01_3012_meaning.mp3',
    audioExample: 'files/01_3012_example.mp3',
    textMeaning: '<i>Municipal</i> means that something belongs to a city or local government.',
    textExample: 'The <b>municipal</b> parking lot downtown can fit one hundred cars.',
    transcription: '[mjuːnísəpəl]',
    textExampleTranslate: 'Муниципальная парковка в центре города может вместить сто автомобилей',
    textMeaningTranslate: 'Муниципальный означает, что что-то принадлежит городскому или местному правительству',
    wordTranslate: 'муниципальный',
  },
  {
    id: '5e9f5ee35eb9e72bc21b006a',
    group: 5,
    page: 0,
    word: 'utilize',
    image: 'files/01_3019.jpg',
    audio: 'files/01_3019.mp3',
    audioMeaning: 'files/01_3019_meaning.mp3',
    audioExample: 'files/01_3019_example.mp3',
    textMeaning: 'To <i>utilize</i> something is to use it for a specific purpose.',
    textExample: 'The team can <b>utilize</b> the lab equipment to complete the experiment.',
    transcription: '[júːtəlàiz]',
    textExampleTranslate: 'Команда может использовать лабораторное оборудование для завершения эксперимента',
    textMeaningTranslate: 'Использовать что-то - значит использовать это для определенной цели',
    wordTranslate: 'использовать',
  },
  {
    id: '5e9f5ee35eb9e72bc21b005f',
    group: 5,
    page: 0,
    word: 'dolphin',
    image: 'files/01_3008.jpg',
    audio: 'files/01_3008.mp3',
    audioMeaning: 'files/01_3008_meaning.mp3',
    audioExample: 'files/01_3008_example.mp3',
    textMeaning: 'A <i>dolphin</i> is a large sea mammal that breathes air.',
    textExample: 'Intelligent <b>dolphins</b> have learned to communicate with humans.',
    transcription: '[dάlfin]',
    textExampleTranslate: 'Умные дельфины научились общаться с людьми',
    textMeaningTranslate: 'Дельфин - это большое морское млекопитающее, которое дышит воздухом',
    wordTranslate: 'дельфин',
  },
  {
    id: '5e9f5ee35eb9e72bc21b0062',
    group: 5,
    page: 0,
    word: 'incidence',
    image: 'files/01_3011.jpg',
    audio: 'files/01_3011.mp3',
    audioMeaning: 'files/01_3011_meaning.mp3',
    audioExample: 'files/01_3011_example.mp3',
    textMeaning: 'The number of times something happens is the <i>incidence</i> of the event.',
    textExample: 'We need to increase the <b>incidence</b> of success in school.',
    transcription: '[ínsədəns]',
    textExampleTranslate: 'Нам нужно увеличить частоту успеха в школе',
    textMeaningTranslate: 'Количество случаев, когда что-то случается, является частотой события',
    wordTranslate: 'частота',
  },
  {
    id: '5e9f5ee35eb9e72bc21b006b',
    group: 5,
    page: 0,
    word: 'whale',
    image: 'files/01_3020.jpg',
    audio: 'files/01_3020.mp3',
    audioMeaning: 'files/01_3020_meaning.mp3',
    audioExample: 'files/01_3020_example.mp3',
    textMeaning: 'A <i>whale</i> is a very large mammal that lives in the ocean.',
    textExample: 'We were surprised when a <b>whale</b> surfaced next to our boat.',
    transcription: '[hweil]',
    textExampleTranslate: 'Мы были удивлены, когда кит всплыл рядом с нашей лодкой',
    textMeaningTranslate: 'Кит - это очень большое млекопитающее, которое живет в океане',
    wordTranslate: 'кит',
  },
];

export default object;
